repos:
-   repo: https://github.com/hakancelik96/unimport
    rev: 0.8.3
    hooks:
      - id: unimport
        args: [--remove, --requirements, --include-star-import, --config, "pyproject.toml"]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
    - id: isort
      args: [--settings-path, "setup.cfg"]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.11.0
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/python/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.0
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear==21.4.3]
- repo: https://github.com/asottile/blacken-docs
  rev: v1.10.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==20.8b1]
